import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@components/header';

const roboto = Roboto({
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['sans-serif', 'arial'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-background text-foreground antialiased`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
