import type { Metadata } from 'next';
import { Roboto, Cairo } from 'next/font/google';
import '../globals.css';
import Header from '@components/header';
import Footer from '@components/footer';
import ThemeProvider from '@components/theme-provider';
import NextTopLoader from 'nextjs-toploader';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { cn } from '@/lib/utils';

const roboto = Roboto({
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['sans-serif', 'arial'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

const cairo = Cairo({
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['sans-serif', 'arial'],
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{
    locale: 'en' | 'ar';
  }>;
}) {
  const locale = (await params).locale;
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
      suppressHydrationWarning
    >
      <body
        className={cn(`bg-background text-foreground antialiased`, {
          [roboto.className]: locale === 'en',
          [cairo.className]: locale === 'ar',
        })}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextTopLoader color="var(--primary)" showSpinner={false} />
          <Header />
          <NextIntlClientProvider messages={messages}>
            <main>{children}</main>
          </NextIntlClientProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
