import type { Metadata } from 'next';
import { Roboto, Cairo } from 'next/font/google';
import '../globals.css';
import Header from '@components/header';
import Footer from '@components/footer';
import ThemeProvider from '@components/theme-provider';
import NextTopLoader from 'nextjs-toploader';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { cn } from '@/lib/utils';
import QueryClientProvider from '@components/query-client-provider';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

const roboto = Roboto({
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['sans-serif', 'arial'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

const cairo = Cairo({
  weight: ['400', '500', '600', '700', '800', '900'],
  fallback: ['sans-serif', 'arial'],
  style: ['normal'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}) {
  const locale = (await params).locale;
  setRequestLocale(locale as 'en' | 'ar');
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      dir={locale === 'ar' ? 'rtl' : 'ltr'}
      suppressHydrationWarning
    >
      <body
        className={cn(`bg-background text-foreground antialiased`, {
          [roboto.className]: locale === 'en',
          [cairo.className]: locale === 'ar',
        })}
      >
        <QueryClientProvider>
          <NextIntlClientProvider messages={messages}>
            <NuqsAdapter>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
              >
                <NextTopLoader color="var(--primary)" showSpinner={false} />
                <Header />
                <main>{children}</main>
                <Footer />
              </ThemeProvider>
            </NuqsAdapter>
          </NextIntlClientProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
